# Generated by Django 4.2 on 2023-05-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteItems',
            new_name='FavoriteItem',
        ),
    ]
