# Generated by Django 4.2 on 2023-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Наименование акции')),
                ('text', models.TextField(max_length=1000, verbose_name='Описание акции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания акции')),
                ('slug', models.SlugField(help_text='Введите слаг', max_length=200, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
