# Generated by Django 4.2 on 2023-06-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_slug_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='products.products', verbose_name='Продукты'),
            preserve_default=False,
        ),
    ]
