# Generated by Django 4.2 on 2023-06-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_favorite_products'),
        ('products', '0010_alter_productreview_score'),
    ]

    operations = [
    ]
