# Generated by Django 4.2 on 2023-06-16 18:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_merge_20230616_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='title',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='products.products', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимум 1'), django.core.validators.MaxValueValidator(5, 'Максимум 5')], verbose_name='Рейтинг'),
        ),
    ]
